name: protoc_plugin
version: 22.0.0
description: A protobuf protoc compiler plugin used to generate Dart code.
repository: https://github.com/google/protobuf.dart/tree/master/protoc_plugin

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  fixnum: ^1.1.1
  path: ^1.9.1
  protobuf: ^4.0.0

dev_dependencies:
  collection: ^1.19.1
  dart_flutter_team_lints: ^3.5.1
  matcher: ^0.12.17
  test: ^1.25.15

executables:
  protoc-gen-dart: protoc_plugin
